# Assemble src\ into the lib\ artifacts DSH loads (no bundler needed):
#   src\host.js   -> lib\index.js   Node half, copied verbatim
#   src\client.js -> lib\client.js  browser half, wrapped in __ModuleLoader__.load's factory
#
# Run after editing src:
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\build.ps1
#
# NOTE (why comments here are ASCII-only):
#   Windows PowerShell 5.1 reads .ps1 files using the ANSI code page unless the file
#   has a UTF-8 BOM. A multi-byte UTF-8 character in a comment can decode to bytes that
#   swallow the following line, silently deleting code. This script is kept ASCII-only
#   and is also written out as UTF-8 *with* BOM so 5.1 and 7 both parse it identically.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$src = Join-Path $root 'src'
$lib = Join-Path $root 'lib'
New-Item -ItemType Directory -Force -Path $lib | Out-Null

# Artifacts are always UTF-8 *without* BOM (the browser decodes them as utf-8).
# Use the static constructor: it behaves the same on 5.1 and 7.
$utf8 = [System.Text.UTF8Encoding]::new($false)

$pkgName = (Get-Content (Join-Path $root 'package.json') -Raw -Encoding utf8 | ConvertFrom-Json).name

# ---- Node half ---------------------------------------------------------------
# Read/write instead of Copy-Item so the artifact is guaranteed BOM-free.
$hostSource = [IO.File]::ReadAllText((Join-Path $src 'host.js'), $utf8)
[IO.File]::WriteAllText((Join-Path $lib 'index.js'), $hostSource, $utf8)

# ---- Browser half ------------------------------------------------------------
$body = [IO.File]::ReadAllText((Join-Path $src 'client.js'), $utf8)
if ($body -match '(?m)^\s*import\s' -or $body -match '(?m)^\s*export\s') {
  throw 'client.js contains import/export: the browser half is loaded via factory(require) and cannot use module syntax'
}

$header = @(
  '// Generated by build.ps1 -- do not edit; edit src\client.js and re-run build.ps1',
  'window.__ModuleLoader__.load({',
  ('  id: ' + (ConvertTo-Json $pkgName -Compress) + ','),
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;'
)
$footer = @(
  '    return module.exports;',
  '  },',
  '});',
  ''
)
$bundle = (($header + @($body.TrimEnd()) + $footer) -join "`n")
[IO.File]::WriteAllText((Join-Path $lib 'client.js'), $bundle, $utf8)

Write-Host ('built: ' + (Join-Path $lib 'index.js'))
Write-Host ('built: ' + (Join-Path $lib 'client.js'))
